application: APPLICATION_NAME
service: SERVICE_NAME
runtime: go
version: VERSION
api_version: go1
threadsafe: true

handlers:
  - url: /.*
    script: _go_app
    secure: always

skip_files:
  - ^(.*/)?glide.lock$
  - ^(.*/)?\.git.*$
  - ^(.*/)?\.vscode$
  - ^(.*/)?\.vscode/.*$
