application: application-name
service: service-name
runtime: go
version: version-name
api_version: go1
threadsafe: true

handlers:
  - url: /.*
    script: _go_app
    secure: always

skip_files:
  - ^(.*/)?glide.lock$
  - ^(.*/)?vendor/.*$
  - ^(.*/)?\.git.*$
  - ^(.*/)?\.vscode$
  - ^(.*/)?\.vscode/.*$
