application: APPLICATION_NAME
service: SERVICE_NAME
runtime: custom
version: VERSION
vm: true
api_version: go1
threadsafe: true

handlers:
  - url: /api/SERVICE_NAME/.*
    script: _go_app
    secure: always